[/Script/UnrealEd.EditorPerProjectUserSettings]
bDisplayActionListItemRefIds=False
BlueprintFavorites=(CustomFavorites=())

[/Script/IntroTutorials.EditorTutorialImportSettings]
bHaveCompletedTutorial=True

[ContentBrowser]
; Default content browser settings for cross-platform dev
